<template>
  <PageSection class="psa">
    <Layer class="background">
      <BackgroundCanvas class="canvas"></BackgroundCanvas>
      <Layer class="color-overlay"></Layer>
    </Layer>
    <Layer class="foreground">
      <h1>Contact</h1>
      <div>
        <p>
          <strong>Address:</strong>
          <br />
          <br />
          <strong>Phone:</strong>
          <br />
          <br />
          <strong>Email:</strong>
          <br />
          <br />
          <strong>Social:</strong>
          <br />
          <br />
        </p>
      </div>
    </Layer>
  </PageSection>
</template>

<script>
import Layer from "../blocks/Layer.vue";
import PageSection from "../blocks/PageSection.vue";
import BackgroundCanvas from "../ui/Background/BackgroundCanvas.vue";

export default {
  name: "content-section-contact",
  components: {
    Layer,
    PageSection,
    BackgroundCanvas,
  },
};
</script>

<style lang="scss" scoped>
.psa {
  .background {
    .canvas {
      z-index: 1;
      filter: blur(4 px) saturate(2) hue-rotate(15deg);
    }

    .color-overlay {
      background: var(--accent);
      background: linear-gradient(0deg, var(--accent), transparent),
        var(--secondary);
      z-index: 5;
      mix-blend-mode: multiply;
    }
  }

  .foreground {
    color: #fff;
    z-index: 50;
  }

  &.active {
    .canvas {
      animation: kenburns-top 15s ease-out both;
    }
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2021-11-11 21:1:22
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation kenburns-top
 * ----------------------------------------
 */

@keyframes kenburns-top {
  0% {
    transform: scale(1) translateY(0) translateX(-50%);
    transform-origin: 50% 16%;
  }
  100% {
    transform: scale(1.25) translateY(-15px) translateX(-50%);
    transform-origin: top;
  }
}
</style>
