<template>
  <PageSection class="psa">
    <Layer class="title-layer">
      <h2 class="section-caption">I <i>am</i><br />your guy</h2>
    </Layer>
  </PageSection>
</template>

<script>
import Layer from "../blocks/Layer.vue";
import PageSection from "../blocks/PageSection.vue";
import PhotoFrame from "../ui/AppContent/PhotoFrame.vue";
export default {
  name: "content-section-ozwild",
  components: { Layer, PageSection, PhotoFrame },
};
</script>

<style lang="scss" scoped>
.psa {
  overflow: hidden;

  .title-layer {
    z-index: 50;
    width: 300vw;
    left: 50%;
    transform: translateX(-50%);

    h2.section-caption {
      text-align: center;
      text-transform: none;
      display: block;
      transform: translate3d(0, 0, 0);
      font-size: calc(4em + 4vw);
      bottom: calc(1em + 2vw);
      margin: 0 auto;
      //transform: translateX(-50%);
      padding: 0;
      position: relative;
      top: 30vh;
      white-space: nowrap;
    }
  }

  &.active {
    h2.section-caption {
      animation: focus-in-contract-bck 2s cubic-bezier(0.25, 0.46, 0.45, 0.94)
        forwards;
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2021-11-5 21:40:53
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation focus-in-contract-bck
 * ----------------------------------------
 */

  @keyframes focus-in-contract-bck {
    0% {
      letter-spacing: 1em;
      transform: translateZ(300px);
      filter: blur(12px);
      opacity: 0;
    }
    100% {
      transform: translateZ(12px);
      filter: blur(0);
      opacity: 1;
    }
  }
}
</style>
